import { readFileSync, mkdirSync, writeFileSync } from 'fs';
import { dirname, join } from 'path';

/**
 * Generates data/System/itemInfo_v5.lua from itemInfo_custom.lua (tbl_custom → tbl).
 */
export function mergeItemInfo(repoRoot, customPath, outputPath) {
  const src = readFileSync(join(repoRoot, customPath), 'utf8');
  const match = src.match(/tbl_custom\s*=\s*(\{[\s\S]*\})\s*$/);
  if (!match) {
    throw new Error('itemInfo_custom.lua: expected tbl_custom = { ... }');
  }

  const body = match[1];
  const out = `-- Auto-generated by ozro-cli client:pack — do not edit.
-- Source: ${customPath}

tbl = ${body}
`;

  const dest = join(repoRoot, outputPath);
  mkdirSync(dirname(dest), { recursive: true });
  writeFileSync(dest, out, 'utf8');
  return dest;
}
