import { readFileSync, mkdirSync, writeFileSync } from 'fs';
import { dirname, join, basename } from 'path';

/**
 * Supplementary itemInfo files (safe — only adds custom IDs, does not replace vanilla DB).
 * RSU / kRO 2020+ clients read itemInfo_v5.lub from the physical System/ folder on disk.
 */
const OUTPUT_NAMES_V5 = [
  'itemInfo_v5.lua',
  'itemInfo_v5.lub'
];

/** Full replacement names — only use with Nemo/WARP ChangeItemInfo patch + loader. */
const OUTPUT_NAMES_EXTRAS = [
  'itemInfo.lua',
  'itemInfo.lub'
];

/**
 * Generates data/System/itemInfo_v5.lua (+ variants) from itemInfo_custom.lua.
 * Returns the list of written paths.
 *
 * @param {object} opts
 * @param {boolean} [opts.extras] - also write itemInfo.lua / itemInfo.lub (replacement; needs exe patch)
 */
export function mergeItemInfo(repoRoot, customPath, outputPath, opts = {}) {
  const src = readFileSync(join(repoRoot, customPath), 'utf8');
  const match = src.match(/tbl_custom\s*=\s*(\{[\s\S]*\})\s*$/);
  if (!match) {
    throw new Error('itemInfo_custom.lua: expected tbl_custom = { ... }');
  }

  const body = match[1];
  const out = `-- Auto-generated by ozro-cli client:iteminfo — do not edit.
-- Source: ${customPath}
-- Install: copy to <client>/System/ on disk (NOT inside ozro.grf).

tbl = ${body}

main = function()
	for ItemID, DESC in pairs(tbl) do
		result, msg = AddItem(ItemID, DESC.unidentifiedDisplayName, DESC.unidentifiedResourceName, DESC.identifiedDisplayName, DESC.identifiedResourceName, DESC.slotCount, DESC.ClassNum, DESC.costume)
		if not result then
			return false, msg
		end
		for k, v in pairs(DESC.unidentifiedDescriptionName) do
			result, msg = AddItemUnidentifiedDesc(ItemID, v)
			if not result then
				return false, msg
			end
		end
		for k, v in pairs(DESC.identifiedDescriptionName) do
			result, msg = AddItemIdentifiedDesc(ItemID, v)
			if not result then
				return false, msg
			end
		end
	end
	return true, "good"
end
`;

  const primary = join(repoRoot, outputPath);
  const outDir = dirname(primary);
  mkdirSync(outDir, { recursive: true });

  const outputNames = opts.extras
    ? [...OUTPUT_NAMES_V5, ...OUTPUT_NAMES_EXTRAS]
    : OUTPUT_NAMES_V5;

  const written = [];
  for (const name of outputNames) {
    const dest = name === basename(outputPath) ? primary : join(outDir, name);
    writeFileSync(dest, out, 'utf8');
    written.push(dest);
  }
  return written;
}
